export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const CHANGE_SORT = 'CHANGE_SORT';
export const ADD_TO_BUFFER = 'ADD_TO_BUFFER';
export const TAKE_FROM_BUFFER = 'TAKE_FROM_BUFFER';
